package net.tclproject.mysteriumlib.render.gecko.common.entities.client.renderer.model;

import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.tclproject.mysteriumlib.render.gecko.animation.model.AnimatedEntityModel;
import net.tclproject.mysteriumlib.render.gecko.animation.render.AnimatedModelRenderer;

public class DragonModel extends AnimatedEntityModel {
   private final AnimatedModelRenderer root;
   private final AnimatedModelRenderer BodyUpper;
   private final AnimatedModelRenderer BodyLower;
   private final AnimatedModelRenderer Tail1;
   private final AnimatedModelRenderer Tail2;
   private final AnimatedModelRenderer Tail3;
   private final AnimatedModelRenderer Tail4;
   private final AnimatedModelRenderer spike16;
   private final AnimatedModelRenderer spike17;
   private final AnimatedModelRenderer Tail5;
   private final AnimatedModelRenderer Club;
   private final AnimatedModelRenderer TailFin2;
   private final AnimatedModelRenderer TailFin1;
   private final AnimatedModelRenderer spike20;
   private final AnimatedModelRenderer spike18;
   private final AnimatedModelRenderer spike19;
   private final AnimatedModelRenderer spike13;
   private final AnimatedModelRenderer spike14;
   private final AnimatedModelRenderer spike15;
   private final AnimatedModelRenderer spike11;
   private final AnimatedModelRenderer spike12;
   private final AnimatedModelRenderer spike10;
   private final AnimatedModelRenderer spike8;
   private final AnimatedModelRenderer spike9;
   private final AnimatedModelRenderer ThighR;
   private final AnimatedModelRenderer LegR;
   private final AnimatedModelRenderer ToeR1;
   private final AnimatedModelRenderer ToeR11;
   private final AnimatedModelRenderer ToeR2;
   private final AnimatedModelRenderer ToeR21;
   private final AnimatedModelRenderer ToeR3;
   private final AnimatedModelRenderer ToeR31;
   private final AnimatedModelRenderer ThighL;
   private final AnimatedModelRenderer LegL;
   private final AnimatedModelRenderer ToeL3;
   private final AnimatedModelRenderer ToeL31;
   private final AnimatedModelRenderer ToeL2;
   private final AnimatedModelRenderer ToeL21;
   private final AnimatedModelRenderer ToeL1;
   private final AnimatedModelRenderer ToeL11;
   private final AnimatedModelRenderer Neck1;
   private final AnimatedModelRenderer Neck2;
   private final AnimatedModelRenderer Neck3;
   private final AnimatedModelRenderer spike1;
   private final AnimatedModelRenderer Head;
   private final AnimatedModelRenderer HeadFront;
   private final AnimatedModelRenderer Teeth2;
   private final AnimatedModelRenderer Teeth1;
   private final AnimatedModelRenderer HornR6;
   private final AnimatedModelRenderer HornR7;
   private final AnimatedModelRenderer Jaw;
   private final AnimatedModelRenderer Teeth3;
   private final AnimatedModelRenderer Teeth4;
   private final AnimatedModelRenderer HornR;
   private final AnimatedModelRenderer HornR2;
   private final AnimatedModelRenderer HornR3;
   private final AnimatedModelRenderer HornL;
   private final AnimatedModelRenderer HornL2;
   private final AnimatedModelRenderer HornL3;
   private final AnimatedModelRenderer HornR8;
   private final AnimatedModelRenderer HornR9;
   private final AnimatedModelRenderer HornL4;
   private final AnimatedModelRenderer HornL5;
   private final AnimatedModelRenderer HornR10;
   private final AnimatedModelRenderer HornR11;
   private final AnimatedModelRenderer HornR4;
   private final AnimatedModelRenderer HornR5;
   private final AnimatedModelRenderer spike2;
   private final AnimatedModelRenderer spike3;
   private final AnimatedModelRenderer spike4;
   private final AnimatedModelRenderer spike5;
   private final AnimatedModelRenderer spike6;
   private final AnimatedModelRenderer spike7;
   private final AnimatedModelRenderer armL1;
   private final AnimatedModelRenderer armL2;
   private final AnimatedModelRenderer armL3;
   private final AnimatedModelRenderer fingerL11;
   private final AnimatedModelRenderer fingerL12;
   private final AnimatedModelRenderer membraneL1;
   private final AnimatedModelRenderer fingerL21;
   private final AnimatedModelRenderer fingerL22;
   private final AnimatedModelRenderer membraneL2;
   private final AnimatedModelRenderer fingerL41;
   private final AnimatedModelRenderer fingerL42;
   private final AnimatedModelRenderer membraneL4;
   private final AnimatedModelRenderer membraneL5;
   private final AnimatedModelRenderer ClawL;
   private final AnimatedModelRenderer ClawL2;
   private final AnimatedModelRenderer ClawL3;
   private final AnimatedModelRenderer fingerL31;
   private final AnimatedModelRenderer fingerL32;
   private final AnimatedModelRenderer membraneL3;
   private final AnimatedModelRenderer membraneL6;
   private final AnimatedModelRenderer armR1;
   private final AnimatedModelRenderer armR2;
   private final AnimatedModelRenderer armR3;
   private final AnimatedModelRenderer fingerR11;
   private final AnimatedModelRenderer fingerR2;
   private final AnimatedModelRenderer membraneR1;
   private final AnimatedModelRenderer fingerR21;
   private final AnimatedModelRenderer fingerR22;
   private final AnimatedModelRenderer membraneR2;
   private final AnimatedModelRenderer fingerR41;
   private final AnimatedModelRenderer fingerR42;
   private final AnimatedModelRenderer membraneR4;
   private final AnimatedModelRenderer membraneR5;
   private final AnimatedModelRenderer ClawR;
   private final AnimatedModelRenderer ClawR2;
   private final AnimatedModelRenderer ClawR3;
   private final AnimatedModelRenderer fingerR31;
   private final AnimatedModelRenderer fingerR32;
   private final AnimatedModelRenderer membraneR3;
   private final AnimatedModelRenderer membraneR6;

   public DragonModel() {
      this.textureWidth = 256;
      this.textureHeight = 128;
      this.root = new AnimatedModelRenderer(this);
      this.root.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.BodyUpper = new AnimatedModelRenderer(this);
      this.BodyUpper.setRotationPoint(0.0F, 11.6F, -10.0F);
      this.root.addChild(this.BodyUpper);
      this.setRotationAngle(this.BodyUpper, 0.0911F, 0.0F, 0.0F);
      this.BodyUpper.cubeList.add(new AdvModelBox(this.BodyUpper, 67, 47, -3.0F, -1.8F, 0.0F, 6, 7, 7, 0.0F, false));
      this.BodyLower = new AnimatedModelRenderer(this);
      this.BodyLower.setRotationPoint(0.0F, 0.0F, 6.7F);
      this.BodyUpper.addChild(this.BodyLower);
      this.setRotationAngle(this.BodyLower, -0.0911F, 0.0F, 0.0F);
      this.BodyLower.cubeList.add(new AdvModelBox(this.BodyLower, 93, 47, -3.5F, -1.5F, 0.0F, 7, 6, 7, 0.0F, false));
      this.Tail1 = new AnimatedModelRenderer(this);
      this.Tail1.setRotationPoint(0.0F, 0.8F, 5.5F);
      this.BodyLower.addChild(this.Tail1);
      this.setRotationAngle(this.Tail1, -0.0911F, 0.0F, 0.0F);
      this.Tail1.cubeList.add(new AdvModelBox(this.Tail1, 75, 35, -2.0F, -2.0F, 1.0F, 4, 5, 6, 0.0F, false));
      this.Tail2 = new AnimatedModelRenderer(this);
      this.Tail2.setRotationPoint(0.0F, -0.1F, 5.8F);
      this.Tail1.addChild(this.Tail2);
      this.setRotationAngle(this.Tail2, -0.4421F, 0.2618F, 0.0F);
      this.Tail2.cubeList.add(new AdvModelBox(this.Tail2, 95, 33, -1.49F, -1.6F, 0.9F, 3, 4, 8, 0.0F, false));
      this.Tail3 = new AnimatedModelRenderer(this);
      this.Tail3.setRotationPoint(0.0F, -0.1F, 7.7F);
      this.Tail2.addChild(this.Tail3);
      this.setRotationAngle(this.Tail3, 0.03F, 0.3142F, 0.0611F);
      this.Tail3.cubeList.add(new AdvModelBox(this.Tail3, 72, 21, -1.5F, -1.3F, 0.9F, 3, 3, 9, 0.0F, false));
      this.Tail4 = new AnimatedModelRenderer(this);
      this.Tail4.setRotationPoint(-1.0F, 0.0F, 8.6F);
      this.Tail3.addChild(this.Tail4);
      this.setRotationAngle(this.Tail4, -0.0262F, 0.5672F, 0.0524F);
      this.Tail4.cubeList.add(new AdvModelBox(this.Tail4, 94, 20, -1.0F, -0.9F, 1.0F, 2, 2, 8, 0.0F, false));
      this.spike16 = new AnimatedModelRenderer(this);
      this.spike16.setRotationPoint(0.0F, -0.3F, 3.8F);
      this.Tail4.addChild(this.spike16);
      this.setRotationAngle(this.spike16, 0.6829F, 0.0F, 0.0F);
      this.spike16.cubeList.add(new AdvModelBox(this.spike16, 34, 34, -0.5F, -0.5F, -0.2F, 1, 1, 2, 0.0F, false));
      this.spike17 = new AnimatedModelRenderer(this);
      this.spike17.setRotationPoint(0.0F, -0.5F, 7.3F);
      this.Tail4.addChild(this.spike17);
      this.setRotationAngle(this.spike17, 0.5918F, 0.0F, 0.0F);
      this.spike17.cubeList.add(new AdvModelBox(this.spike17, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.Tail5 = new AnimatedModelRenderer(this);
      this.Tail5.setRotationPoint(-1.0F, 0.0F, 7.6F);
      this.Tail4.addChild(this.Tail5);
      this.setRotationAngle(this.Tail5, 0.1122F, 0.9303F, 0.2932F);
      this.Tail5.cubeList.add(new AdvModelBox(this.Tail5, 94, 9, -1.01F, -0.9F, 1.0F, 2, 2, 8, 0.0F, false));
      this.Club = new AnimatedModelRenderer(this);
      this.Club.setRotationPoint(0.0F, -0.4F, 7.5F);
      this.Tail5.addChild(this.Club);
      this.Club.cubeList.add(new AdvModelBox(this.Club, 42, 17, -2.0F, -0.4F, 1.0F, 4, 2, 8, 0.0F, false));
      this.TailFin2 = new AnimatedModelRenderer(this);
      this.TailFin2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Club.addChild(this.TailFin2);
      this.setRotationAngle(this.TailFin2, 0.0F, 0.7854F, 0.0873F);
      this.TailFin2.cubeList.add(new AdvModelBox(this.TailFin2, 70, 70, -9.0F, 0.29F, 1.31F, 9, 0, 12, 0.0F, false));
      this.TailFin1 = new AnimatedModelRenderer(this);
      this.TailFin1.setRotationPoint(0.1F, 0.0F, 0.0F);
      this.Club.addChild(this.TailFin1);
      this.setRotationAngle(this.TailFin1, 0.0F, -0.7854F, -0.0873F);
      this.TailFin1.cubeList.add(new AdvModelBox(this.TailFin1, 70, 70, 0.0F, 0.3F, 1.31F, 9, 0, 12, 0.0F, true));
      this.spike20 = new AnimatedModelRenderer(this);
      this.spike20.setRotationPoint(0.0F, 0.0F, 3.0F);
      this.Club.addChild(this.spike20);
      this.setRotationAngle(this.spike20, 0.3643F, 0.0F, 0.0F);
      this.spike20.cubeList.add(new AdvModelBox(this.spike20, 22, 34, -0.5F, -0.5F, 0.0F, 1, 1, 3, 0.0F, false));
      this.spike18 = new AnimatedModelRenderer(this);
      this.spike18.setRotationPoint(0.0F, -0.3F, 3.8F);
      this.Tail5.addChild(this.spike18);
      this.setRotationAngle(this.spike18, 0.6829F, 0.0F, 0.0F);
      this.spike18.cubeList.add(new AdvModelBox(this.spike18, 34, 34, -0.5F, -0.5F, -0.2F, 1, 1, 2, 0.0F, false));
      this.spike19 = new AnimatedModelRenderer(this);
      this.spike19.setRotationPoint(0.0F, -0.5F, 7.3F);
      this.Tail5.addChild(this.spike19);
      this.setRotationAngle(this.spike19, 0.5009F, 0.0F, 0.0F);
      this.spike19.cubeList.add(new AdvModelBox(this.spike19, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike13 = new AnimatedModelRenderer(this);
      this.spike13.setRotationPoint(0.0F, -0.9F, 2.0F);
      this.Tail3.addChild(this.spike13);
      this.setRotationAngle(this.spike13, 0.4554F, 0.0F, 0.0F);
      this.spike13.cubeList.add(new AdvModelBox(this.spike13, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike14 = new AnimatedModelRenderer(this);
      this.spike14.setRotationPoint(0.0F, -0.8F, 5.5F);
      this.Tail3.addChild(this.spike14);
      this.setRotationAngle(this.spike14, 0.5009F, 0.0F, 0.0F);
      this.spike14.cubeList.add(new AdvModelBox(this.spike14, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike15 = new AnimatedModelRenderer(this);
      this.spike15.setRotationPoint(0.0F, -0.6F, 8.9F);
      this.Tail3.addChild(this.spike15);
      this.setRotationAngle(this.spike15, 0.6374F, 0.0F, 0.0F);
      this.spike15.cubeList.add(new AdvModelBox(this.spike15, 34, 34, -0.5F, -0.5F, -0.2F, 1, 1, 2, 0.0F, false));
      this.spike11 = new AnimatedModelRenderer(this);
      this.spike11.setRotationPoint(0.0F, -1.2F, 2.3F);
      this.Tail2.addChild(this.spike11);
      this.setRotationAngle(this.spike11, 0.5009F, 0.0F, 0.0F);
      this.spike11.cubeList.add(new AdvModelBox(this.spike11, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike12 = new AnimatedModelRenderer(this);
      this.spike12.setRotationPoint(0.0F, -1.1F, 5.8F);
      this.Tail2.addChild(this.spike12);
      this.setRotationAngle(this.spike12, 0.5009F, 0.0F, 0.0F);
      this.spike12.cubeList.add(new AdvModelBox(this.spike12, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike10 = new AnimatedModelRenderer(this);
      this.spike10.setRotationPoint(0.0F, -1.6F, 4.6F);
      this.Tail1.addChild(this.spike10);
      this.setRotationAngle(this.spike10, 0.5918F, 0.0F, 0.0F);
      this.spike10.cubeList.add(new AdvModelBox(this.spike10, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike8 = new AnimatedModelRenderer(this);
      this.spike8.setRotationPoint(0.0F, -0.8F, 2.8F);
      this.BodyLower.addChild(this.spike8);
      this.setRotationAngle(this.spike8, 0.5463F, 0.0F, 0.0F);
      this.spike8.cubeList.add(new AdvModelBox(this.spike8, 22, 34, -0.5F, -0.5F, 0.0F, 1, 1, 3, 0.0F, false));
      this.spike9 = new AnimatedModelRenderer(this);
      this.spike9.setRotationPoint(0.0F, -0.9F, 6.5F);
      this.BodyLower.addChild(this.spike9);
      this.setRotationAngle(this.spike9, 0.5463F, 0.0F, 0.0F);
      this.spike9.cubeList.add(new AdvModelBox(this.spike9, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.ThighR = new AnimatedModelRenderer(this);
      this.ThighR.setRotationPoint(3.7F, 1.6F, 6.0F);
      this.BodyLower.addChild(this.ThighR);
      this.setRotationAngle(this.ThighR, -0.192F, 0.0F, 0.0F);
      this.ThighR.cubeList.add(new AdvModelBox(this.ThighR, 0, 23, -1.57F, -0.5F, -2.0F, 3, 7, 4, 0.0F, false));
      this.LegR = new AnimatedModelRenderer(this);
      this.LegR.setRotationPoint(0.0F, 4.3F, 1.9F);
      this.ThighR.addChild(this.LegR);
      this.setRotationAngle(this.LegR, -0.3316F, 0.0F, 0.0F);
      this.LegR.cubeList.add(new AdvModelBox(this.LegR, 15, 23, -1.0F, -0.5F, 0.0F, 2, 7, 2, 0.0F, false));
      this.ToeR1 = new AnimatedModelRenderer(this);
      this.ToeR1.setRotationPoint(-1.0F, 6.1F, 1.0F);
      this.LegR.addChild(this.ToeR1);
      this.setRotationAngle(this.ToeR1, 0.4363F, 0.1745F, 0.0F);
      this.ToeR1.cubeList.add(new AdvModelBox(this.ToeR1, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeR11 = new AnimatedModelRenderer(this);
      this.ToeR11.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeR1.addChild(this.ToeR11);
      this.setRotationAngle(this.ToeR11, 0.1745F, 0.0F, 0.0F);
      this.ToeR11.cubeList.add(new AdvModelBox(this.ToeR11, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, true));
      this.ToeR2 = new AnimatedModelRenderer(this);
      this.ToeR2.setRotationPoint(0.0F, 5.9F, 0.4F);
      this.LegR.addChild(this.ToeR2);
      this.setRotationAngle(this.ToeR2, 0.5236F, 0.0F, 0.0F);
      this.ToeR2.cubeList.add(new AdvModelBox(this.ToeR2, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeR21 = new AnimatedModelRenderer(this);
      this.ToeR21.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeR2.addChild(this.ToeR21);
      this.setRotationAngle(this.ToeR21, 0.1745F, 0.0F, 0.0F);
      this.ToeR21.cubeList.add(new AdvModelBox(this.ToeR21, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, true));
      this.ToeR3 = new AnimatedModelRenderer(this);
      this.ToeR3.setRotationPoint(1.0F, 6.1F, 1.0F);
      this.LegR.addChild(this.ToeR3);
      this.setRotationAngle(this.ToeR3, 0.4363F, -0.1745F, 0.0F);
      this.ToeR3.cubeList.add(new AdvModelBox(this.ToeR3, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeR31 = new AnimatedModelRenderer(this);
      this.ToeR31.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeR3.addChild(this.ToeR31);
      this.setRotationAngle(this.ToeR31, 0.1745F, 0.0F, 0.0F);
      this.ToeR31.cubeList.add(new AdvModelBox(this.ToeR31, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, true));
      this.ThighL = new AnimatedModelRenderer(this);
      this.ThighL.setRotationPoint(-3.7F, 1.6F, 6.0F);
      this.BodyLower.addChild(this.ThighL);
      this.setRotationAngle(this.ThighL, -0.192F, 0.0F, 0.0F);
      this.ThighL.cubeList.add(new AdvModelBox(this.ThighL, 0, 23, -1.57F, -0.5F, -2.0F, 3, 7, 4, 0.0F, true));
      this.LegL = new AnimatedModelRenderer(this);
      this.LegL.setRotationPoint(0.0F, 4.3F, 1.9F);
      this.ThighL.addChild(this.LegL);
      this.setRotationAngle(this.LegL, -0.3316F, 0.0F, 0.0F);
      this.LegL.cubeList.add(new AdvModelBox(this.LegL, 15, 23, -1.0F, -0.5F, 0.0F, 2, 7, 2, 0.0F, true));
      this.ToeL3 = new AnimatedModelRenderer(this);
      this.ToeL3.setRotationPoint(-1.0F, 6.1F, 1.0F);
      this.LegL.addChild(this.ToeL3);
      this.setRotationAngle(this.ToeL3, 0.4363F, 0.1745F, 0.0F);
      this.ToeL3.cubeList.add(new AdvModelBox(this.ToeL3, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeL31 = new AnimatedModelRenderer(this);
      this.ToeL31.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeL3.addChild(this.ToeL31);
      this.setRotationAngle(this.ToeL31, 0.1745F, 0.0F, 0.0F);
      this.ToeL31.cubeList.add(new AdvModelBox(this.ToeL31, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, false));
      this.ToeL2 = new AnimatedModelRenderer(this);
      this.ToeL2.setRotationPoint(0.0F, 5.9F, 0.4F);
      this.LegL.addChild(this.ToeL2);
      this.setRotationAngle(this.ToeL2, 0.5236F, 0.0F, 0.0F);
      this.ToeL2.cubeList.add(new AdvModelBox(this.ToeL2, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeL21 = new AnimatedModelRenderer(this);
      this.ToeL21.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeL2.addChild(this.ToeL21);
      this.setRotationAngle(this.ToeL21, 0.1745F, 0.0F, 0.0F);
      this.ToeL21.cubeList.add(new AdvModelBox(this.ToeL21, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, false));
      this.ToeL1 = new AnimatedModelRenderer(this);
      this.ToeL1.setRotationPoint(1.0F, 6.1F, 1.0F);
      this.LegL.addChild(this.ToeL1);
      this.setRotationAngle(this.ToeL1, 0.4363F, -0.1745F, 0.0F);
      this.ToeL1.cubeList.add(new AdvModelBox(this.ToeL1, 2, 64, -0.5F, -0.8F, -3.1F, 1, 2, 4, 0.0F, false));
      this.ToeL11 = new AnimatedModelRenderer(this);
      this.ToeL11.setRotationPoint(0.0F, 0.0F, -2.45F);
      this.ToeL1.addChild(this.ToeL11);
      this.setRotationAngle(this.ToeL11, 0.1745F, 0.0F, 0.0F);
      this.ToeL11.cubeList.add(new AdvModelBox(this.ToeL11, 3, 73, -0.5F, -0.8F, -2.5F, 1, 2, 2, 0.0F, false));
      this.Neck1 = new AnimatedModelRenderer(this);
      this.Neck1.setRotationPoint(0.0F, 0.5F, 1.8F);
      this.BodyUpper.addChild(this.Neck1);
      this.setRotationAngle(this.Neck1, -0.3927F, 0.0F, 0.0F);
      this.Neck1.cubeList.add(new AdvModelBox(this.Neck1, 55, 43, -2.5F, -2.0F, -5.0F, 5, 6, 4, 0.0F, false));
      this.Neck2 = new AnimatedModelRenderer(this);
      this.Neck2.setRotationPoint(0.0F, 1.2F, -4.7F);
      this.Neck1.addChild(this.Neck2);
      this.setRotationAngle(this.Neck2, -0.3081F, 0.0F, 0.0F);
      this.Neck2.cubeList.add(new AdvModelBox(this.Neck2, 23, 39, -2.0F, -2.7F, -5.1F, 4, 5, 7, 0.0F, false));
      this.Neck3 = new AnimatedModelRenderer(this);
      this.Neck3.setRotationPoint(0.0F, -0.8F, -4.4F);
      this.Neck2.addChild(this.Neck3);
      this.setRotationAngle(this.Neck3, 0.5835F, 0.0F, 0.0F);
      this.Neck3.cubeList.add(new AdvModelBox(this.Neck3, 24, 63, -1.5F, -1.6F, -7.1F, 3, 4, 8, 0.0F, false));
      this.spike1 = new AnimatedModelRenderer(this);
      this.spike1.setRotationPoint(0.0F, -1.4F, -4.4F);
      this.Neck3.addChild(this.spike1);
      this.setRotationAngle(this.spike1, 0.5009F, 0.0F, 0.0F);
      this.spike1.cubeList.add(new AdvModelBox(this.spike1, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.Head = new AnimatedModelRenderer(this);
      this.Head.setRotationPoint(0.0F, 0.1F, -5.5F);
      this.Neck3.addChild(this.Head);
      this.setRotationAngle(this.Head, 0.3142F, 0.0F, 0.0F);
      this.Head.cubeList.add(new AdvModelBox(this.Head, 6, 54, -2.5F, -2.2F, -4.0F, 5, 4, 4, 0.0F, false));
      this.HeadFront = new AnimatedModelRenderer(this);
      this.HeadFront.setRotationPoint(0.0F, -0.63F, -3.3F);
      this.Head.addChild(this.HeadFront);
      this.setRotationAngle(this.HeadFront, -0.0668F, 0.0F, 0.0F);
      this.HeadFront.cubeList.add(new AdvModelBox(this.HeadFront, 5, 43, -2.0F, -1.5F, -5.0F, 4, 3, 6, 0.0F, false));
      this.Teeth2 = new AnimatedModelRenderer(this);
      this.Teeth2.setRotationPoint(-0.4F, -0.7F, 0.1F);
      this.HeadFront.addChild(this.Teeth2);
      this.Teeth2.cubeList.add(new AdvModelBox(this.Teeth2, 6, 16, -1.52F, 2.0F, -5.02F, 2, 1, 5, 0.0F, true));
      this.Teeth1 = new AnimatedModelRenderer(this);
      this.Teeth1.setRotationPoint(0.4F, -0.7F, 0.1F);
      this.HeadFront.addChild(this.Teeth1);
      this.Teeth1.cubeList.add(new AdvModelBox(this.Teeth1, 6, 16, -0.48F, 2.0F, -5.02F, 2, 1, 5, 0.0F, false));
      this.HornR6 = new AnimatedModelRenderer(this);
      this.HornR6.setRotationPoint(0.0F, -0.87F, -5.6F);
      this.HeadFront.addChild(this.HornR6);
      this.setRotationAngle(this.HornR6, 0.7285F, 0.0F, 0.0F);
      this.HornR6.cubeList.add(new AdvModelBox(this.HornR6, 71, 36, -0.5F, 0.0F, 1.0F, 1, 2, 2, 0.0F, false));
      this.HornR7 = new AnimatedModelRenderer(this);
      this.HornR7.setRotationPoint(0.0F, 0.77F, 2.5F);
      this.HornR6.addChild(this.HornR7);
      this.setRotationAngle(this.HornR7, -0.3187F, 0.0F, 0.0F);
      this.HornR7.cubeList.add(new AdvModelBox(this.HornR7, 62, 30, -0.5F, -0.83F, 0.0F, 1, 1, 2, 0.0F, true));
      this.Jaw = new AnimatedModelRenderer(this);
      this.Jaw.setRotationPoint(0.0F, 1.4F, -3.2F);
      this.Head.addChild(this.Jaw);
      this.setRotationAngle(this.Jaw, -0.1244F, 0.0F, 0.0F);
      this.Jaw.cubeList.add(new AdvModelBox(this.Jaw, 33, 55, -2.0F, -0.4F, -5.5F, 4, 1, 6, 0.0F, false));
      this.Teeth3 = new AnimatedModelRenderer(this);
      this.Teeth3.setRotationPoint(0.6F, 0.1F, -0.3F);
      this.Jaw.addChild(this.Teeth3);
      this.setRotationAngle(this.Teeth3, 0.0524F, 0.0F, -3.1416F);
      this.Teeth3.cubeList.add(new AdvModelBox(this.Teeth3, 7, 17, -1.41F, 0.1F, -5.3F, 2, 2, 4, 0.0F, true));
      this.Teeth4 = new AnimatedModelRenderer(this);
      this.Teeth4.setRotationPoint(-0.6F, 0.1F, -0.3F);
      this.Jaw.addChild(this.Teeth4);
      this.setRotationAngle(this.Teeth4, 0.0524F, 0.0F, -3.1416F);
      this.Teeth4.cubeList.add(new AdvModelBox(this.Teeth4, 7, 17, -0.59F, 0.1F, -5.3F, 2, 2, 4, 0.0F, false));
      this.HornR = new AnimatedModelRenderer(this);
      this.HornR.setRotationPoint(1.8F, -1.6F, -1.6F);
      this.Head.addChild(this.HornR);
      this.setRotationAngle(this.HornR, 0.1745F, 0.3316F, -0.192F);
      this.HornR.cubeList.add(new AdvModelBox(this.HornR, 59, 34, -0.5F, -0.5F, 0.0F, 1, 2, 4, 0.0F, false));
      this.HornR2 = new AnimatedModelRenderer(this);
      this.HornR2.setRotationPoint(0.5F, 0.3F, 3.3F);
      this.HornR.addChild(this.HornR2);
      this.setRotationAngle(this.HornR2, -0.0698F, 0.0F, 0.0F);
      this.HornR2.cubeList.add(new AdvModelBox(this.HornR2, 46, 36, -1.01F, -0.8F, 0.0F, 1, 1, 3, 0.0F, false));
      this.HornR3 = new AnimatedModelRenderer(this);
      this.HornR3.setRotationPoint(-0.5F, 0.0F, 2.6F);
      this.HornR2.addChild(this.HornR3);
      this.setRotationAngle(this.HornR3, 0.0524F, 0.0F, 0.0F);
      this.HornR3.cubeList.add(new AdvModelBox(this.HornR3, 55, 30, -0.49F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.HornL = new AnimatedModelRenderer(this);
      this.HornL.setRotationPoint(-1.8F, -1.6F, -1.6F);
      this.Head.addChild(this.HornL);
      this.setRotationAngle(this.HornL, 0.1745F, -0.3316F, 0.192F);
      this.HornL.cubeList.add(new AdvModelBox(this.HornL, 59, 34, -0.5F, -0.5F, 0.0F, 1, 2, 4, 0.0F, true));
      this.HornL2 = new AnimatedModelRenderer(this);
      this.HornL2.setRotationPoint(0.5F, 0.3F, 3.3F);
      this.HornL.addChild(this.HornL2);
      this.setRotationAngle(this.HornL2, -0.0698F, 0.0F, 0.0F);
      this.HornL2.cubeList.add(new AdvModelBox(this.HornL2, 46, 36, -0.99F, -0.8F, 0.0F, 1, 1, 3, 0.0F, true));
      this.HornL3 = new AnimatedModelRenderer(this);
      this.HornL3.setRotationPoint(-0.5F, 0.0F, 2.6F);
      this.HornL2.addChild(this.HornL3);
      this.setRotationAngle(this.HornL3, 0.0524F, 0.0F, 0.0F);
      this.HornL3.cubeList.add(new AdvModelBox(this.HornL3, 55, 30, -0.49F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.HornR8 = new AnimatedModelRenderer(this);
      this.HornR8.setRotationPoint(1.8F, -0.1F, -1.8F);
      this.Head.addChild(this.HornR8);
      this.setRotationAngle(this.HornR8, -0.1745F, 0.3142F, 0.0F);
      this.HornR8.cubeList.add(new AdvModelBox(this.HornR8, 36, 28, -0.5F, 0.0F, 0.0F, 1, 1, 4, 0.0F, false));
      this.HornR9 = new AnimatedModelRenderer(this);
      this.HornR9.setRotationPoint(0.0F, 0.8F, 3.6F);
      this.HornR8.addChild(this.HornR9);
      this.setRotationAngle(this.HornR9, 0.0873F, 0.0F, 0.0F);
      this.HornR9.cubeList.add(new AdvModelBox(this.HornR9, 47, 30, -0.53F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.HornL4 = new AnimatedModelRenderer(this);
      this.HornL4.setRotationPoint(-1.8F, -0.1F, -1.8F);
      this.Head.addChild(this.HornL4);
      this.setRotationAngle(this.HornL4, -0.1745F, -0.3142F, 0.0F);
      this.HornL4.cubeList.add(new AdvModelBox(this.HornL4, 36, 28, -0.5F, 0.0F, 0.0F, 1, 1, 4, 0.0F, true));
      this.HornL5 = new AnimatedModelRenderer(this);
      this.HornL5.setRotationPoint(0.0F, 0.8F, 3.6F);
      this.HornL4.addChild(this.HornL5);
      this.setRotationAngle(this.HornL5, 0.0873F, 0.0F, 0.0F);
      this.HornL5.cubeList.add(new AdvModelBox(this.HornL5, 47, 30, -0.47F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.HornR10 = new AnimatedModelRenderer(this);
      this.HornR10.setRotationPoint(0.8F, -2.1F, -1.8F);
      this.Head.addChild(this.HornR10);
      this.setRotationAngle(this.HornR10, 0.3491F, 0.3142F, 0.0F);
      this.HornR10.cubeList.add(new AdvModelBox(this.HornR10, 59, 34, -0.5F, 0.0F, 0.0F, 1, 1, 4, 0.0F, false));
      this.HornR11 = new AnimatedModelRenderer(this);
      this.HornR11.setRotationPoint(0.0F, 0.8F, 3.6F);
      this.HornR10.addChild(this.HornR11);
      this.setRotationAngle(this.HornR11, 0.0524F, 0.0F, 0.0F);
      this.HornR11.cubeList.add(new AdvModelBox(this.HornR11, 47, 30, -0.53F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.HornR4 = new AnimatedModelRenderer(this);
      this.HornR4.setRotationPoint(-0.8F, -2.1F, -1.8F);
      this.Head.addChild(this.HornR4);
      this.setRotationAngle(this.HornR4, 0.3491F, -0.3142F, 0.0F);
      this.HornR4.cubeList.add(new AdvModelBox(this.HornR4, 59, 34, -0.5F, 0.0F, 0.0F, 1, 1, 4, 0.0F, false));
      this.HornR5 = new AnimatedModelRenderer(this);
      this.HornR5.setRotationPoint(0.0F, 0.8F, 3.6F);
      this.HornR4.addChild(this.HornR5);
      this.setRotationAngle(this.HornR5, 0.0524F, 0.0F, 0.0F);
      this.HornR5.cubeList.add(new AdvModelBox(this.HornR5, 47, 30, -0.53F, -0.8F, 0.0F, 1, 1, 2, 0.0F, true));
      this.spike2 = new AnimatedModelRenderer(this);
      this.spike2.setRotationPoint(0.0F, -1.1F, -1.2F);
      this.Neck3.addChild(this.spike2);
      this.setRotationAngle(this.spike2, 0.5918F, 0.0F, 0.0F);
      this.spike2.cubeList.add(new AdvModelBox(this.spike2, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike3 = new AnimatedModelRenderer(this);
      this.spike3.setRotationPoint(0.0F, -2.3F, -2.4F);
      this.Neck2.addChild(this.spike3);
      this.setRotationAngle(this.spike3, 0.9032F, 0.0F, 0.0F);
      this.spike3.cubeList.add(new AdvModelBox(this.spike3, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike4 = new AnimatedModelRenderer(this);
      this.spike4.setRotationPoint(0.0F, -1.6F, -4.0F);
      this.Neck1.addChild(this.spike4);
      this.setRotationAngle(this.spike4, 0.6829F, 0.0F, 0.0F);
      this.spike4.cubeList.add(new AdvModelBox(this.spike4, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike5 = new AnimatedModelRenderer(this);
      this.spike5.setRotationPoint(0.0F, -1.5F, 1.0F);
      this.BodyUpper.addChild(this.spike5);
      this.setRotationAngle(this.spike5, 0.5918F, 0.0F, 0.0F);
      this.spike5.cubeList.add(new AdvModelBox(this.spike5, 34, 34, -0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F, false));
      this.spike6 = new AnimatedModelRenderer(this);
      this.spike6.setRotationPoint(0.0F, -1.1F, 3.5F);
      this.BodyUpper.addChild(this.spike6);
      this.setRotationAngle(this.spike6, 0.6374F, 0.0F, 0.0F);
      this.spike6.cubeList.add(new AdvModelBox(this.spike6, 22, 34, -0.5F, -0.5F, 0.0F, 1, 1, 3, 0.0F, false));
      this.spike7 = new AnimatedModelRenderer(this);
      this.spike7.setRotationPoint(0.0F, -1.0F, 6.5F);
      this.BodyUpper.addChild(this.spike7);
      this.setRotationAngle(this.spike7, 0.5463F, 0.0F, 0.0F);
      this.spike7.cubeList.add(new AdvModelBox(this.spike7, 22, 34, -0.5F, -0.5F, 0.0F, 1, 1, 3, 0.0F, true));
      this.armL1 = new AnimatedModelRenderer(this);
      this.armL1.setRotationPoint(0.3F, -0.7F, 3.0F);
      this.BodyUpper.addChild(this.armL1);
      this.setRotationAngle(this.armL1, 0.1745F, 0.0456F, -1.5359F);
      this.armL1.cubeList.add(new AdvModelBox(this.armL1, 170, 31, -1.0F, -0.5F, -2.0F, 2, 12, 4, 0.0F, true));
      this.armL2 = new AnimatedModelRenderer(this);
      this.armL2.setRotationPoint(0.1F, 11.3F, -0.1F);
      this.armL1.addChild(this.armL2);
      this.setRotationAngle(this.armL2, -0.3142F, 0.3142F, 0.6283F);
      this.armL2.cubeList.add(new AdvModelBox(this.armL2, 189, 27, -1.0F, -1.5F, -1.4F, 2, 21, 3, 0.0F, true));
      this.armL3 = new AnimatedModelRenderer(this);
      this.armL3.setRotationPoint(0.5F, 10.3F, -0.1F);
      this.armL2.addChild(this.armL3);
      this.fingerL11 = new AnimatedModelRenderer(this);
      this.fingerL11.setRotationPoint(0.0F, 9.0F, 0.0F);
      this.armL3.addChild(this.fingerL11);
      this.setRotationAngle(this.fingerL11, 1.6232F, 0.0F, 0.0F);
      this.fingerL11.cubeList.add(new AdvModelBox(this.fingerL11, 145, 23, -0.5F, -0.5F, -1.0F, 1, 18, 2, 0.0F, true));
      this.fingerL12 = new AnimatedModelRenderer(this);
      this.fingerL12.setRotationPoint(0.0F, 17.4F, 0.1F);
      this.fingerL11.addChild(this.fingerL12);
      this.setRotationAngle(this.fingerL12, 0.1745F, 0.0F, 0.0F);
      this.fingerL12.cubeList.add(new AdvModelBox(this.fingerL12, 152, 23, -0.48F, -0.5F, -1.0F, 1, 17, 2, 0.0F, true));
      this.membraneL1 = new AnimatedModelRenderer(this);
      this.membraneL1.setRotationPoint(0.5F, 0.4F, -0.5F);
      this.fingerL11.addChild(this.membraneL1);
      this.setRotationAngle(this.membraneL1, 0.0911F, 0.0F, 0.0F);
      this.membraneL1.cubeList.add(new AdvModelBox(this.membraneL1, 54, 73, -0.5F, -1.0F, 0.0F, 0, 33, 18, 0.0F, true));
      this.fingerL21 = new AnimatedModelRenderer(this);
      this.fingerL21.setRotationPoint(-0.2F, 8.3F, 0.0F);
      this.armL3.addChild(this.fingerL21);
      this.setRotationAngle(this.fingerL21, 1.8364F, 0.0F, 0.0F);
      this.fingerL21.cubeList.add(new AdvModelBox(this.fingerL21, 145, 23, -0.5F, -0.5F, -1.0F, 1, 17, 2, 0.0F, true));
      this.fingerL22 = new AnimatedModelRenderer(this);
      this.fingerL22.setRotationPoint(0.0F, 16.4F, 0.1F);
      this.fingerL21.addChild(this.fingerL22);
      this.setRotationAngle(this.fingerL22, 0.1745F, 0.0F, 0.0F);
      this.fingerL22.cubeList.add(new AdvModelBox(this.fingerL22, 160, 23, -0.48F, -0.5F, -1.0F, 1, 16, 2, 0.0F, true));
      this.membraneL2 = new AnimatedModelRenderer(this);
      this.membraneL2.setRotationPoint(0.5F, 0.4F, -0.9F);
      this.fingerL21.addChild(this.membraneL2);
      this.setRotationAngle(this.membraneL2, 0.0911F, 0.0F, 0.0F);
      this.membraneL2.cubeList.add(new AdvModelBox(this.membraneL2, 54, 75, -0.5F, -0.5F, 0.0F, 0, 32, 18, 0.0F, true));
      this.fingerL41 = new AnimatedModelRenderer(this);
      this.fingerL41.setRotationPoint(0.1F, 18.3F, -0.1F);
      this.armL2.addChild(this.fingerL41);
      this.setRotationAngle(this.fingerL41, 2.322F, 0.0F, 0.0F);
      this.fingerL41.cubeList.add(new AdvModelBox(this.fingerL41, 145, 23, -0.5F, -0.5F, -1.0F, 1, 16, 2, 0.0F, true));
      this.fingerL42 = new AnimatedModelRenderer(this);
      this.fingerL42.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.fingerL41.addChild(this.fingerL42);
      this.setRotationAngle(this.fingerL42, 0.1745F, 0.0F, 0.0F);
      this.fingerL42.cubeList.add(new AdvModelBox(this.fingerL42, 151, 52, -0.48F, -0.5F, -1.0F, 1, 15, 2, 0.0F, true));
      this.membraneL4 = new AnimatedModelRenderer(this);
      this.membraneL4.setRotationPoint(0.5F, 0.2F, -1.1F);
      this.fingerL41.addChild(this.membraneL4);
      this.setRotationAngle(this.membraneL4, 0.0873F, 0.0F, 0.0F);
      this.membraneL4.cubeList.add(new AdvModelBox(this.membraneL4, 54, 77, -0.5F, -0.5F, 0.0F, 0, 30, 18, 0.0F, true));
      this.membraneL5 = new AnimatedModelRenderer(this);
      this.membraneL5.setRotationPoint(0.5F, 17.8F, 2.0F);
      this.armL2.addChild(this.membraneL5);
      this.setRotationAngle(this.membraneL5, 2.5042F, 0.0F, 0.0F);
      this.membraneL5.cubeList.add(new AdvModelBox(this.membraneL5, 106, 73, -0.5F, -0.5F, 0.0F, 0, 27, 18, 0.0F, true));
      this.ClawL = new AnimatedModelRenderer(this);
      this.ClawL.setRotationPoint(-0.1F, 19.0F, -0.1F);
      this.armL2.addChild(this.ClawL);
      this.setRotationAngle(this.ClawL, 0.0F, -0.6981F, 1.5708F);
      this.ClawL.cubeList.add(new AdvModelBox(this.ClawL, 128, 44, -1.7F, -0.8F, -0.5F, 2, 2, 1, 0.0F, true));
      this.ClawL2 = new AnimatedModelRenderer(this);
      this.ClawL2.setRotationPoint(-2.0F, 0.0F, 0.0F);
      this.ClawL.addChild(this.ClawL2);
      this.ClawL2.cubeList.add(new AdvModelBox(this.ClawL2, 128, 52, -1.7F, -0.8F, -0.5F, 2, 2, 1, 0.0F, true));
      this.ClawL3 = new AnimatedModelRenderer(this);
      this.ClawL3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.ClawL2.addChild(this.ClawL3);
      this.ClawL3.cubeList.add(new AdvModelBox(this.ClawL3, 128, 61, -1.2F, 0.7F, -0.5F, 2, 1, 1, 0.0F, true));
      this.fingerL31 = new AnimatedModelRenderer(this);
      this.fingerL31.setRotationPoint(0.2F, 18.3F, -0.1F);
      this.armL2.addChild(this.fingerL31);
      this.setRotationAngle(this.fingerL31, 2.0769F, 0.0F, 0.0F);
      this.fingerL31.cubeList.add(new AdvModelBox(this.fingerL31, 145, 23, -0.5F, -0.5F, -1.0F, 1, 16, 2, 0.0F, true));
      this.fingerL32 = new AnimatedModelRenderer(this);
      this.fingerL32.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.fingerL31.addChild(this.fingerL32);
      this.setRotationAngle(this.fingerL32, 0.1745F, 0.0F, 0.0F);
      this.fingerL32.cubeList.add(new AdvModelBox(this.fingerL32, 151, 52, -0.48F, -0.5F, -1.0F, 1, 15, 2, 0.0F, true));
      this.membraneL3 = new AnimatedModelRenderer(this);
      this.membraneL3.setRotationPoint(0.5F, 0.2F, -1.1F);
      this.fingerL31.addChild(this.membraneL3);
      this.setRotationAngle(this.membraneL3, 0.0911F, 0.0F, 0.0F);
      this.membraneL3.cubeList.add(new AdvModelBox(this.membraneL3, 54, 77, -0.5F, -0.5F, 0.0F, 0, 30, 18, 0.0F, true));
      this.membraneL6 = new AnimatedModelRenderer(this);
      this.membraneL6.setRotationPoint(0.57F, -1.9F, 2.5F);
      this.armL1.addChild(this.membraneL6);
      this.setRotationAngle(this.membraneL6, -1.457F, 0.0F, 0.0F);
      this.membraneL6.cubeList.add(new AdvModelBox(this.membraneL6, 156, 82, -0.5F, -8.8F, 0.8F, 0, 11, 13, 0.0F, true));
      this.armR1 = new AnimatedModelRenderer(this);
      this.armR1.setRotationPoint(-1.3F, -0.7F, 3.0F);
      this.BodyUpper.addChild(this.armR1);
      this.setRotationAngle(this.armR1, 0.1745F, -0.0456F, 1.5359F);
      this.armR1.cubeList.add(new AdvModelBox(this.armR1, 170, 31, -1.0F, -0.5F, -2.0F, 2, 12, 4, 0.0F, false));
      this.armR2 = new AnimatedModelRenderer(this);
      this.armR2.setRotationPoint(-0.1F, 11.3F, -0.1F);
      this.armR1.addChild(this.armR2);
      this.setRotationAngle(this.armR2, -0.3142F, -0.3142F, -0.6283F);
      this.armR2.cubeList.add(new AdvModelBox(this.armR2, 189, 27, -1.0F, -1.5F, -1.4F, 2, 21, 3, 0.0F, false));
      this.armR3 = new AnimatedModelRenderer(this);
      this.armR3.setRotationPoint(-0.5F, 11.3F, -0.1F);
      this.armR2.addChild(this.armR3);
      this.fingerR11 = new AnimatedModelRenderer(this);
      this.fingerR11.setRotationPoint(0.0F, 8.0F, 0.0F);
      this.armR3.addChild(this.fingerR11);
      this.setRotationAngle(this.fingerR11, 1.6232F, 0.0F, 0.0F);
      this.fingerR11.cubeList.add(new AdvModelBox(this.fingerR11, 145, 23, -0.5F, -0.5F, -1.0F, 1, 18, 2, 0.0F, false));
      this.fingerR2 = new AnimatedModelRenderer(this);
      this.fingerR2.setRotationPoint(0.0F, 17.4F, 0.1F);
      this.fingerR11.addChild(this.fingerR2);
      this.setRotationAngle(this.fingerR2, 0.1745F, 0.0F, 0.0F);
      this.fingerR2.cubeList.add(new AdvModelBox(this.fingerR2, 152, 23, -0.5F, -0.5F, -1.0F, 1, 17, 2, 0.0F, false));
      this.membraneR1 = new AnimatedModelRenderer(this);
      this.membraneR1.setRotationPoint(-0.5F, 0.4F, -0.5F);
      this.fingerR11.addChild(this.membraneR1);
      this.setRotationAngle(this.membraneR1, 0.0911F, 0.0F, 0.0F);
      this.membraneR1.cubeList.add(new AdvModelBox(this.membraneR1, 54, 73, 0.5F, -1.0F, 0.0F, 0, 33, 18, 0.0F, false));
      this.fingerR21 = new AnimatedModelRenderer(this);
      this.fingerR21.setRotationPoint(0.2F, 7.3F, 0.0F);
      this.armR3.addChild(this.fingerR21);
      this.setRotationAngle(this.fingerR21, 1.8364F, 0.0F, 0.0F);
      this.fingerR21.cubeList.add(new AdvModelBox(this.fingerR21, 145, 23, -0.5F, -0.5F, -1.0F, 1, 17, 2, 0.0F, false));
      this.fingerR22 = new AnimatedModelRenderer(this);
      this.fingerR22.setRotationPoint(0.0F, 16.4F, 0.1F);
      this.fingerR21.addChild(this.fingerR22);
      this.setRotationAngle(this.fingerR22, 0.1745F, 0.0F, 0.0F);
      this.fingerR22.cubeList.add(new AdvModelBox(this.fingerR22, 160, 23, -0.52F, -0.5F, -1.0F, 1, 16, 2, 0.0F, false));
      this.membraneR2 = new AnimatedModelRenderer(this);
      this.membraneR2.setRotationPoint(-0.5F, 0.4F, -0.9F);
      this.fingerR21.addChild(this.membraneR2);
      this.setRotationAngle(this.membraneR2, 0.0911F, 0.0F, 0.0F);
      this.membraneR2.cubeList.add(new AdvModelBox(this.membraneR2, 54, 75, 0.5F, -0.5F, 0.0F, 0, 32, 18, 0.0F, false));
      this.fingerR41 = new AnimatedModelRenderer(this);
      this.fingerR41.setRotationPoint(-0.1F, 18.3F, -0.1F);
      this.armR2.addChild(this.fingerR41);
      this.setRotationAngle(this.fingerR41, 2.322F, 0.0F, 0.0F);
      this.fingerR41.cubeList.add(new AdvModelBox(this.fingerR41, 145, 23, -0.5F, -0.5F, -1.0F, 1, 16, 2, 0.0F, false));
      this.fingerR42 = new AnimatedModelRenderer(this);
      this.fingerR42.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.fingerR41.addChild(this.fingerR42);
      this.setRotationAngle(this.fingerR42, 0.1745F, 0.0F, 0.0F);
      this.fingerR42.cubeList.add(new AdvModelBox(this.fingerR42, 151, 52, -0.52F, -0.5F, -1.0F, 1, 15, 2, 0.0F, false));
      this.membraneR4 = new AnimatedModelRenderer(this);
      this.membraneR4.setRotationPoint(-0.5F, 0.2F, -1.1F);
      this.fingerR41.addChild(this.membraneR4);
      this.setRotationAngle(this.membraneR4, 0.0873F, 0.0F, 0.0F);
      this.membraneR4.cubeList.add(new AdvModelBox(this.membraneR4, 54, 77, 0.5F, -0.5F, 0.0F, 0, 30, 18, 0.0F, false));
      this.membraneR5 = new AnimatedModelRenderer(this);
      this.membraneR5.setRotationPoint(-0.5F, 17.8F, 2.0F);
      this.armR2.addChild(this.membraneR5);
      this.setRotationAngle(this.membraneR5, 2.5042F, 0.0F, 0.0F);
      this.membraneR5.cubeList.add(new AdvModelBox(this.membraneR5, 106, 73, 0.5F, -0.5F, 0.0F, 0, 27, 18, 0.0F, false));
      this.ClawR = new AnimatedModelRenderer(this);
      this.ClawR.setRotationPoint(0.1F, 19.0F, -0.1F);
      this.armR2.addChild(this.ClawR);
      this.setRotationAngle(this.ClawR, 3.1416F, -0.6981F, 1.5708F);
      this.ClawR.cubeList.add(new AdvModelBox(this.ClawR, 128, 44, -1.7F, -0.8F, -0.5F, 2, 2, 1, 0.0F, true));
      this.ClawR2 = new AnimatedModelRenderer(this);
      this.ClawR2.setRotationPoint(-2.0F, 0.0F, 0.0F);
      this.ClawR.addChild(this.ClawR2);
      this.ClawR2.cubeList.add(new AdvModelBox(this.ClawR2, 128, 52, -1.7F, -0.8F, -0.5F, 2, 2, 1, 0.0F, true));
      this.ClawR3 = new AnimatedModelRenderer(this);
      this.ClawR3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.ClawR2.addChild(this.ClawR3);
      this.ClawR3.cubeList.add(new AdvModelBox(this.ClawR3, 128, 61, -1.2F, 0.7F, -0.5F, 2, 1, 1, 0.0F, true));
      this.fingerR31 = new AnimatedModelRenderer(this);
      this.fingerR31.setRotationPoint(-0.2F, 18.3F, -0.1F);
      this.armR2.addChild(this.fingerR31);
      this.setRotationAngle(this.fingerR31, 2.0792F, 0.0F, 0.0F);
      this.fingerR31.cubeList.add(new AdvModelBox(this.fingerR31, 145, 23, -0.5F, -0.5F, -1.0F, 1, 16, 2, 0.0F, false));
      this.fingerR32 = new AnimatedModelRenderer(this);
      this.fingerR32.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.fingerR31.addChild(this.fingerR32);
      this.setRotationAngle(this.fingerR32, 0.1745F, 0.0F, 0.0F);
      this.fingerR32.cubeList.add(new AdvModelBox(this.fingerR32, 151, 52, -0.52F, -0.5F, -1.0F, 1, 15, 2, 0.0F, false));
      this.membraneR3 = new AnimatedModelRenderer(this);
      this.membraneR3.setRotationPoint(-0.5F, 0.2F, -1.1F);
      this.fingerR31.addChild(this.membraneR3);
      this.setRotationAngle(this.membraneR3, 0.0911F, 0.0F, 0.0F);
      this.membraneR3.cubeList.add(new AdvModelBox(this.membraneR3, 54, 77, 0.5F, -0.5F, 0.0F, 0, 30, 18, 0.0F, false));
      this.membraneR6 = new AnimatedModelRenderer(this);
      this.membraneR6.setRotationPoint(-0.57F, -1.9F, 2.5F);
      this.armR1.addChild(this.membraneR6);
      this.setRotationAngle(this.membraneR6, -1.457F, 0.0F, 0.0F);
      this.membraneR6.cubeList.add(new AdvModelBox(this.membraneR6, 156, 82, 0.5F, -8.8F, 0.8F, 0, 11, 13, 0.0F, false));
      this.root.setModelRendererName("root");
      this.BodyUpper.setModelRendererName("BodyUpper");
      this.BodyLower.setModelRendererName("BodyLower");
      this.Tail1.setModelRendererName("Tail1");
      this.Tail2.setModelRendererName("Tail2");
      this.Tail3.setModelRendererName("Tail3");
      this.Tail4.setModelRendererName("Tail4");
      this.spike16.setModelRendererName("spike16");
      this.spike17.setModelRendererName("spike17");
      this.Tail5.setModelRendererName("Tail5");
      this.Club.setModelRendererName("Club");
      this.TailFin2.setModelRendererName("TailFin2");
      this.TailFin1.setModelRendererName("TailFin1");
      this.spike20.setModelRendererName("spike20");
      this.spike18.setModelRendererName("spike18");
      this.spike19.setModelRendererName("spike19");
      this.spike13.setModelRendererName("spike13");
      this.spike14.setModelRendererName("spike14");
      this.spike15.setModelRendererName("spike15");
      this.spike11.setModelRendererName("spike11");
      this.spike12.setModelRendererName("spike12");
      this.spike10.setModelRendererName("spike10");
      this.spike8.setModelRendererName("spike8");
      this.spike9.setModelRendererName("spike9");
      this.ThighR.setModelRendererName("ThighR");
      this.LegR.setModelRendererName("LegR");
      this.ToeR1.setModelRendererName("ToeR1");
      this.ToeR11.setModelRendererName("ToeR11");
      this.ToeR2.setModelRendererName("ToeR2");
      this.ToeR21.setModelRendererName("ToeR21");
      this.ToeR3.setModelRendererName("ToeR3");
      this.ToeR31.setModelRendererName("ToeR31");
      this.ThighL.setModelRendererName("ThighL");
      this.LegL.setModelRendererName("LegL");
      this.ToeL3.setModelRendererName("ToeL3");
      this.ToeL31.setModelRendererName("ToeL31");
      this.ToeL2.setModelRendererName("ToeL2");
      this.ToeL21.setModelRendererName("ToeL21");
      this.ToeL1.setModelRendererName("ToeL1");
      this.ToeL11.setModelRendererName("ToeL11");
      this.Neck1.setModelRendererName("Neck1");
      this.Neck2.setModelRendererName("Neck2");
      this.Neck3.setModelRendererName("Neck3");
      this.spike1.setModelRendererName("spike1");
      this.Head.setModelRendererName("Head");
      this.HeadFront.setModelRendererName("HeadFront");
      this.Teeth2.setModelRendererName("Teeth2");
      this.Teeth1.setModelRendererName("Teeth1");
      this.HornR6.setModelRendererName("HornR6");
      this.HornR7.setModelRendererName("HornR7");
      this.Jaw.setModelRendererName("Jaw");
      this.Teeth3.setModelRendererName("Teeth3");
      this.Teeth4.setModelRendererName("Teeth4");
      this.HornR.setModelRendererName("HornR");
      this.HornR2.setModelRendererName("HornR2");
      this.HornR3.setModelRendererName("HornR3");
      this.HornL.setModelRendererName("HornL");
      this.HornL2.setModelRendererName("HornL2");
      this.HornL3.setModelRendererName("HornL3");
      this.HornR8.setModelRendererName("HornR8");
      this.HornR9.setModelRendererName("HornR9");
      this.HornL4.setModelRendererName("HornR9");
      this.HornL5.setModelRendererName("HornL5");
      this.HornR10.setModelRendererName("HornR10");
      this.HornR11.setModelRendererName("HornR11");
      this.HornR4.setModelRendererName("HornR4");
      this.HornR5.setModelRendererName("HornR5");
      this.spike2.setModelRendererName("spike2");
      this.spike3.setModelRendererName("spike3");
      this.spike4.setModelRendererName("spike4");
      this.spike5.setModelRendererName("spike5");
      this.spike6.setModelRendererName("spike6");
      this.spike7.setModelRendererName("spike7");
      this.armL1.setModelRendererName("armL1");
      this.armL2.setModelRendererName("armL2");
      this.armL3.setModelRendererName("armL3");
      this.fingerL11.setModelRendererName("fingerL11");
      this.fingerL12.setModelRendererName("fingerL12");
      this.membraneL1.setModelRendererName("membraneL1");
      this.fingerL21.setModelRendererName("fingerL21");
      this.fingerL22.setModelRendererName("fingerL22");
      this.membraneL2.setModelRendererName("membraneL2");
      this.fingerL41.setModelRendererName("fingerL41");
      this.fingerL42.setModelRendererName("fingerL42");
      this.membraneL4.setModelRendererName("membraneL4");
      this.membraneL5.setModelRendererName("membraneL5");
      this.ClawL.setModelRendererName("ClawL");
      this.ClawL2.setModelRendererName("ClawL2");
      this.ClawL3.setModelRendererName("ClawL3");
      this.fingerL31.setModelRendererName("fingerL31");
      this.fingerL32.setModelRendererName("fingerL32");
      this.membraneL3.setModelRendererName("membraneL3");
      this.membraneL6.setModelRendererName("membraneL6");
      this.armR1.setModelRendererName("armR1");
      this.armR2.setModelRendererName("armR2");
      this.armR3.setModelRendererName("armR3");
      this.fingerR11.setModelRendererName("fingerR11");
      this.fingerR2.setModelRendererName("fingerR2");
      this.membraneR1.setModelRendererName("membraneR1");
      this.fingerR21.setModelRendererName("fingerR21");
      this.fingerR22.setModelRendererName("fingerR22");
      this.membraneR2.setModelRendererName("membraneR2");
      this.fingerR41.setModelRendererName("fingerR41");
      this.fingerR42.setModelRendererName("fingerR42");
      this.membraneR4.setModelRendererName("membraneR4");
      this.membraneR5.setModelRendererName("membraneR5");
      this.ClawR.setModelRendererName("ClawR");
      this.ClawR2.setModelRendererName("ClawR2");
      this.ClawR3.setModelRendererName("ClawR3");
      this.fingerR31.setModelRendererName("fingerR31");
      this.fingerR32.setModelRendererName("fingerR32");
      this.membraneR3.setModelRendererName("membraneR3");
      this.membraneR6.setModelRendererName("membraneR6");
      this.registerModelRenderer(this.root);
      this.registerModelRenderer(this.BodyUpper);
      this.registerModelRenderer(this.BodyLower);
      this.registerModelRenderer(this.Tail1);
      this.registerModelRenderer(this.Tail2);
      this.registerModelRenderer(this.Tail3);
      this.registerModelRenderer(this.Tail4);
      this.registerModelRenderer(this.spike16);
      this.registerModelRenderer(this.spike17);
      this.registerModelRenderer(this.Tail5);
      this.registerModelRenderer(this.Club);
      this.registerModelRenderer(this.TailFin2);
      this.registerModelRenderer(this.TailFin1);
      this.registerModelRenderer(this.spike20);
      this.registerModelRenderer(this.spike18);
      this.registerModelRenderer(this.spike19);
      this.registerModelRenderer(this.spike13);
      this.registerModelRenderer(this.spike14);
      this.registerModelRenderer(this.spike15);
      this.registerModelRenderer(this.spike11);
      this.registerModelRenderer(this.spike12);
      this.registerModelRenderer(this.spike10);
      this.registerModelRenderer(this.spike8);
      this.registerModelRenderer(this.spike9);
      this.registerModelRenderer(this.ThighR);
      this.registerModelRenderer(this.LegR);
      this.registerModelRenderer(this.ToeR1);
      this.registerModelRenderer(this.ToeR11);
      this.registerModelRenderer(this.ToeR2);
      this.registerModelRenderer(this.ToeR21);
      this.registerModelRenderer(this.ToeR3);
      this.registerModelRenderer(this.ToeR31);
      this.registerModelRenderer(this.ThighL);
      this.registerModelRenderer(this.LegL);
      this.registerModelRenderer(this.ToeL3);
      this.registerModelRenderer(this.ToeL31);
      this.registerModelRenderer(this.ToeL2);
      this.registerModelRenderer(this.ToeL21);
      this.registerModelRenderer(this.ToeL1);
      this.registerModelRenderer(this.ToeL11);
      this.registerModelRenderer(this.Neck1);
      this.registerModelRenderer(this.Neck2);
      this.registerModelRenderer(this.Neck3);
      this.registerModelRenderer(this.spike1);
      this.registerModelRenderer(this.Head);
      this.registerModelRenderer(this.HeadFront);
      this.registerModelRenderer(this.Teeth2);
      this.registerModelRenderer(this.Teeth1);
      this.registerModelRenderer(this.HornR6);
      this.registerModelRenderer(this.HornR7);
      this.registerModelRenderer(this.Jaw);
      this.registerModelRenderer(this.Teeth3);
      this.registerModelRenderer(this.Teeth4);
      this.registerModelRenderer(this.HornR);
      this.registerModelRenderer(this.HornR2);
      this.registerModelRenderer(this.HornR3);
      this.registerModelRenderer(this.HornL);
      this.registerModelRenderer(this.HornL2);
      this.registerModelRenderer(this.HornL3);
      this.registerModelRenderer(this.HornR8);
      this.registerModelRenderer(this.HornR9);
      this.registerModelRenderer(this.HornL4);
      this.registerModelRenderer(this.HornL5);
      this.registerModelRenderer(this.HornR10);
      this.registerModelRenderer(this.HornR11);
      this.registerModelRenderer(this.HornR4);
      this.registerModelRenderer(this.HornR5);
      this.registerModelRenderer(this.spike2);
      this.registerModelRenderer(this.spike3);
      this.registerModelRenderer(this.spike4);
      this.registerModelRenderer(this.spike5);
      this.registerModelRenderer(this.spike6);
      this.registerModelRenderer(this.spike7);
      this.registerModelRenderer(this.armL1);
      this.registerModelRenderer(this.armL2);
      this.registerModelRenderer(this.armL3);
      this.registerModelRenderer(this.fingerL11);
      this.registerModelRenderer(this.fingerL12);
      this.registerModelRenderer(this.membraneL1);
      this.registerModelRenderer(this.fingerL21);
      this.registerModelRenderer(this.fingerL22);
      this.registerModelRenderer(this.membraneL2);
      this.registerModelRenderer(this.fingerL41);
      this.registerModelRenderer(this.fingerL42);
      this.registerModelRenderer(this.membraneL4);
      this.registerModelRenderer(this.membraneL5);
      this.registerModelRenderer(this.ClawL);
      this.registerModelRenderer(this.ClawL2);
      this.registerModelRenderer(this.ClawL3);
      this.registerModelRenderer(this.fingerL31);
      this.registerModelRenderer(this.fingerL32);
      this.registerModelRenderer(this.membraneL3);
      this.registerModelRenderer(this.membraneL6);
      this.registerModelRenderer(this.armR1);
      this.registerModelRenderer(this.armR2);
      this.registerModelRenderer(this.armR3);
      this.registerModelRenderer(this.fingerR11);
      this.registerModelRenderer(this.fingerR2);
      this.registerModelRenderer(this.membraneR1);
      this.registerModelRenderer(this.fingerR21);
      this.registerModelRenderer(this.fingerR22);
      this.registerModelRenderer(this.membraneR2);
      this.registerModelRenderer(this.fingerR41);
      this.registerModelRenderer(this.fingerR42);
      this.registerModelRenderer(this.membraneR4);
      this.registerModelRenderer(this.membraneR5);
      this.registerModelRenderer(this.ClawR);
      this.registerModelRenderer(this.ClawR2);
      this.registerModelRenderer(this.ClawR3);
      this.registerModelRenderer(this.fingerR31);
      this.registerModelRenderer(this.fingerR32);
      this.registerModelRenderer(this.membraneR3);
      this.registerModelRenderer(this.membraneR6);
      this.rootBones.add(this.root);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.root.render(f5);
   }

   public void setRotationAngle(AnimatedModelRenderer AnimatedModelRenderer, float x, float y, float z) {
      AnimatedModelRenderer.rotateAngleX = x;
      AnimatedModelRenderer.rotateAngleY = y;
      AnimatedModelRenderer.rotateAngleZ = z;
   }

   public ResourceLocation getAnimationFileLocation() {
      return new ResourceLocation("arsmagica2", "animations/dragon2.animation.json");
   }
}
