package net.tclproject.mysteriumlib.render.gecko.common.entities.client.renderer.model;

import net.ilexiconn.llibrary.client.model.ModelAnimator;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelRenderer;
import net.ilexiconn.llibrary.server.animation.IAnimatedEntity;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.tclproject.mysteriumlib.render.gecko.common.entities.entity.specific.iceandfire.EntityMyrmexSentinel;
import net.tclproject.mysteriumlib.render.gecko.iceandfire.ModelUtils;

public class ModelMyrmexSentinel extends ModelMyrmexBase {
   public AdvancedModelRenderer Body2;
   public AdvancedModelRenderer Body3;
   public AdvancedModelRenderer Body1;
   public AdvancedModelRenderer legTopR2;
   public AdvancedModelRenderer legTopR2_1;
   public AdvancedModelRenderer legTopR3;
   public AdvancedModelRenderer legTopR3_1;
   public AdvancedModelRenderer Tail1;
   public AdvancedModelRenderer legMidR3;
   public AdvancedModelRenderer legBottomR3;
   public AdvancedModelRenderer legMidR3_1;
   public AdvancedModelRenderer legBottomR3_1;
   public AdvancedModelRenderer Tail2;
   public AdvancedModelRenderer Tail3;
   public AdvancedModelRenderer Tail4;
   public AdvancedModelRenderer Tail5;
   public AdvancedModelRenderer Tail6;
   public AdvancedModelRenderer Tail7;
   public AdvancedModelRenderer Tail8;
   public AdvancedModelRenderer Tail9;
   public AdvancedModelRenderer Stinger;
   public AdvancedModelRenderer Neck1;
   public AdvancedModelRenderer legTopR1;
   public AdvancedModelRenderer legTopR1_1;
   public AdvancedModelRenderer HeadBase;
   public AdvancedModelRenderer EyeR;
   public AdvancedModelRenderer MandibleL;
   public AdvancedModelRenderer MandibleR;
   public AdvancedModelRenderer EyeL;
   public AdvancedModelRenderer legMidR1;
   public AdvancedModelRenderer legBottomR1;
   public AdvancedModelRenderer legMidR1_1;
   public AdvancedModelRenderer legBottomR1_1;
   public AdvancedModelRenderer legMidR2;
   public AdvancedModelRenderer legBottomR2;
   public AdvancedModelRenderer legMidR2_1;
   public AdvancedModelRenderer legBottomR2_1;
   private ModelAnimator animator;

   public ModelMyrmexSentinel() {
      this.textureWidth = 128;
      this.textureHeight = 128;
      this.MandibleR = new AdvancedModelRenderer(this, 0, 25);
      this.MandibleR.mirror = true;
      this.MandibleR.setRotationPoint(-3.4F, 3.7F, -7.7F);
      this.MandibleR.addBox(-2.0F, -2.51F, -5.1F, 4, 2, 6, 0.0F);
      this.setRotateAngle(this.MandibleR, 0.17453292F, -0.18203785F, 0.0F);
      this.legTopR2_1 = new AdvancedModelRenderer(this, 0, 54);
      this.legTopR2_1.mirror = true;
      this.legTopR2_1.setRotationPoint(-3.3F, 1.0F, 1.6F);
      this.legTopR2_1.addBox(-1.0F, 0.0F, -1.5F, 2, 10, 3, 0.0F);
      this.setRotateAngle(this.legTopR2_1, -0.5235988F, -0.5235988F, 0.6981317F);
      this.MandibleL = new AdvancedModelRenderer(this, 0, 25);
      this.MandibleL.setRotationPoint(3.4F, 3.7F, -7.7F);
      this.MandibleL.addBox(-2.0F, -2.51F, -5.1F, 4, 2, 6, 0.0F);
      this.setRotateAngle(this.MandibleL, 0.17453292F, 0.18203785F, 0.0F);
      this.legTopR1 = new AdvancedModelRenderer(this, 0, 75);
      this.legTopR1.setRotationPoint(-3.3F, 0.0F, -8.4F);
      this.legTopR1.addBox(-1.5F, 0.0F, -1.5F, 3, 17, 3, 0.0F);
      this.setRotateAngle(this.legTopR1, 1.2217305F, 0.0F, 0.18203785F);
      this.legBottomR1_1 = new AdvancedModelRenderer(this, 0, 98);
      this.legBottomR1_1.setRotationPoint(0.0F, 17.4F, 0.0F);
      this.legBottomR1_1.addBox(-1.5F, 0.0F, -2.9F, 3, 20, 6, 0.0F);
      this.setRotateAngle(this.legBottomR1_1, 2.9670596F, 0.0F, 0.0F);
      this.legMidR1_1 = new AdvancedModelRenderer(this, 12, 75);
      this.legMidR1_1.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.legMidR1_1.addBox(-1.0F, 0.0F, -1.0F, 2, 17, 4, 0.0F);
      this.setRotateAngle(this.legMidR1_1, -2.7925267F, 0.0F, 0.0F);
      this.legTopR1_1 = new AdvancedModelRenderer(this, 0, 75);
      this.legTopR1_1.mirror = true;
      this.legTopR1_1.setRotationPoint(3.3F, 0.0F, -8.4F);
      this.legTopR1_1.addBox(-1.5F, 0.0F, -1.5F, 3, 17, 3, 0.0F);
      this.setRotateAngle(this.legTopR1_1, 1.2217305F, 0.0F, -0.18203785F);
      this.EyeL = new AdvancedModelRenderer(this, 39, 0);
      this.EyeL.setRotationPoint(4.0F, -0.3F, -3.5F);
      this.EyeL.addBox(-1.5F, -1.0F, -3.5F, 3, 2, 7, 0.0F);
      this.setRotateAngle(this.EyeL, 0.2268928F, -0.08726646F, 1.5707964F);
      this.legBottomR3 = new AdvancedModelRenderer(this, 22, 51);
      this.legBottomR3.setRotationPoint(0.0F, 10.4F, 0.0F);
      this.legBottomR3.addBox(-1.01F, 0.0F, -0.9F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.legBottomR3, 0.0F, 0.0F, -1.3203416F);
      this.legTopR3_1 = new AdvancedModelRenderer(this, 0, 54);
      this.legTopR3_1.setRotationPoint(3.3F, 1.0F, 1.6F);
      this.legTopR3_1.addBox(-1.0F, 0.0F, -1.5F, 2, 10, 3, 0.0F);
      this.setRotateAngle(this.legTopR3_1, 0.5009095F, -0.22759093F, -0.6457718F);
      this.Body2 = new AdvancedModelRenderer(this, 91, 57);
      this.Body2.setRotationPoint(0.0F, 4.0F, -6.0F);
      this.Body2.addBox(-3.0F, -2.7F, -1.1F, 6, 7, 4, 0.0F);
      this.setRotateAngle(this.Body2, -0.045553092F, 0.0F, 0.0F);
      this.legBottomR3_1 = new AdvancedModelRenderer(this, 22, 51);
      this.legBottomR3_1.mirror = true;
      this.legBottomR3_1.setRotationPoint(0.0F, 10.4F, 0.0F);
      this.legBottomR3_1.addBox(-1.01F, 0.0F, -0.9F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.legBottomR3_1, 0.0F, 0.0F, 1.3203416F);
      this.Neck1 = new AdvancedModelRenderer(this, 32, 22);
      this.Neck1.setRotationPoint(0.0F, -2.0F, -13.0F);
      this.Neck1.addBox(-2.5F, -2.0F, -5.5F, 5, 5, 7, 0.0F);
      this.setRotateAngle(this.Neck1, 0.3642502F, 0.0F, 0.0F);
      this.Tail6 = new AdvancedModelRenderer(this, 100, 20);
      this.Tail6.setRotationPoint(0.0F, 0.7F, 3.2F);
      this.Tail6.addBox(-2.5F, -3.5F, -0.1F, 5, 6, 7, 0.0F);
      this.setRotateAngle(this.Tail6, 0.18203785F, 0.0F, 0.0F);
      this.legMidR1 = new AdvancedModelRenderer(this, 12, 75);
      this.legMidR1.setRotationPoint(0.0F, 15.4F, 0.1F);
      this.legMidR1.addBox(-1.0F, 0.0F, -1.0F, 2, 17, 4, 0.0F);
      this.setRotateAngle(this.legMidR1, -2.7925267F, 0.0F, 0.0F);
      this.legBottomR2_1 = new AdvancedModelRenderer(this, 22, 51);
      this.legBottomR2_1.setRotationPoint(0.0F, 10.4F, 0.0F);
      this.legBottomR2_1.addBox(-1.01F, 0.0F, -0.9F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.legBottomR2_1, 0.0F, 0.0F, -1.3203416F);
      this.Body1 = new AdvancedModelRenderer(this, 34, 47);
      this.Body1.setRotationPoint(0.0F, -3.7F, -4.0F);
      this.Body1.addBox(-3.5F, -4.1F, -12.8F, 7, 9, 20, 0.0F);
      this.setRotateAngle(this.Body1, -0.8196066F, 0.0F, 0.0F);
      this.Tail7 = new AdvancedModelRenderer(this, 65, 35);
      this.Tail7.setRotationPoint(0.0F, -1.0F, 6.4F);
      this.Tail7.addBox(-2.0F, -2.2F, -1.3F, 4, 5, 5, 0.0F);
      this.setRotateAngle(this.Tail7, 0.4098033F, 0.0F, 0.0F);
      this.legBottomR1 = new AdvancedModelRenderer(this, 0, 98);
      this.legBottomR1.setRotationPoint(0.0F, 17.4F, 0.0F);
      this.legBottomR1.addBox(-1.02F, 0.0F, -2.9F, 3, 20, 6, 0.0F);
      this.setRotateAngle(this.legBottomR1, 2.9670596F, 0.0F, 0.0F);
      this.Tail2 = new AdvancedModelRenderer(this, 100, 20);
      this.Tail2.setRotationPoint(0.0F, 0.7F, 3.2F);
      this.Tail2.addBox(-2.5F, -3.5F, -0.1F, 5, 6, 7, 0.0F);
      this.setRotateAngle(this.Tail2, 0.4553564F, 0.0F, 0.0F);
      this.EyeR = new AdvancedModelRenderer(this, 39, 0);
      this.EyeR.mirror = true;
      this.EyeR.setRotationPoint(-4.0F, -0.3F, -3.5F);
      this.EyeR.addBox(-1.5F, -1.0F, -3.5F, 3, 2, 7, 0.0F);
      this.setRotateAngle(this.EyeR, 0.2268928F, 0.08726646F, -1.5707964F);
      this.legTopR3 = new AdvancedModelRenderer(this, 0, 54);
      this.legTopR3.mirror = true;
      this.legTopR3.setRotationPoint(-3.3F, 1.0F, 1.6F);
      this.legTopR3.addBox(-1.0F, 0.0F, -1.5F, 2, 10, 3, 0.0F);
      this.setRotateAngle(this.legTopR3, 0.5009095F, 0.22759093F, 0.6457718F);
      this.Stinger = new AdvancedModelRenderer(this, 60, 0);
      this.Stinger.setRotationPoint(0.0F, -0.4F, 6.0F);
      this.Stinger.addBox(-1.0F, -2.7F, -1.7F, 2, 10, 2, 0.0F);
      this.setRotateAngle(this.Stinger, 2.8684487F, 0.0F, 0.0F);
      this.legMidR2_1 = new AdvancedModelRenderer(this, 11, 50);
      this.legMidR2_1.setRotationPoint(0.0F, 8.4F, 0.1F);
      this.legMidR2_1.addBox(-1.5F, 0.0F, -1.0F, 3, 12, 2, 0.0F);
      this.setRotateAngle(this.legMidR2_1, 0.0F, 0.0F, 1.1383038F);
      this.legMidR3 = new AdvancedModelRenderer(this, 11, 50);
      this.legMidR3.setRotationPoint(0.0F, 8.4F, 0.1F);
      this.legMidR3.addBox(-1.5F, 0.0F, -1.0F, 3, 12, 2, 0.0F);
      this.setRotateAngle(this.legMidR3, 0.0F, 0.0F, 1.1383038F);
      this.Tail8 = new AdvancedModelRenderer(this, 80, 38);
      this.Tail8.setRotationPoint(0.0F, 0.6F, 1.2F);
      this.Tail8.addBox(-5.5F, -3.2F, 0.9F, 11, 7, 11, 0.0F);
      this.setRotateAngle(this.Tail8, 0.68294734F, 0.0F, 0.0F);
      this.legTopR2 = new AdvancedModelRenderer(this, 0, 54);
      this.legTopR2.setRotationPoint(3.3F, 1.0F, 1.6F);
      this.legTopR2.addBox(-1.0F, 0.0F, -1.5F, 2, 10, 3, 0.0F);
      this.setRotateAngle(this.legTopR2, -0.5235988F, 0.5235988F, -0.6981317F);
      this.Tail3 = new AdvancedModelRenderer(this, 65, 35);
      this.Tail3.setRotationPoint(0.0F, -1.0F, 6.4F);
      this.Tail3.addBox(-2.0F, -2.2F, -1.3F, 4, 5, 5, 0.0F);
      this.setRotateAngle(this.Tail3, 0.68294734F, 0.0F, 0.0F);
      this.legBottomR2 = new AdvancedModelRenderer(this, 22, 51);
      this.legBottomR2.mirror = true;
      this.legBottomR2.setRotationPoint(0.0F, 10.4F, 0.0F);
      this.legBottomR2.addBox(-1.01F, 0.0F, -0.9F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.legBottomR2, 0.0F, 0.0F, 1.3203416F);
      this.Tail1 = new AdvancedModelRenderer(this, 65, 35);
      this.Tail1.setRotationPoint(0.0F, -0.4F, 6.4F);
      this.Tail1.addBox(-2.0F, -2.2F, -0.1F, 4, 5, 5, 0.0F);
      this.setRotateAngle(this.Tail1, -0.045553092F, 0.0F, 0.0F);
      this.HeadBase = new AdvancedModelRenderer(this, 0, 0);
      this.HeadBase.setRotationPoint(0.0F, -1.1F, -4.4F);
      this.HeadBase.addBox(-4.0F, -2.51F, -10.1F, 8, 6, 10, 0.0F);
      this.setRotateAngle(this.HeadBase, 1.0927507F, 0.0F, 0.0F);
      this.Tail5 = new AdvancedModelRenderer(this, 65, 35);
      this.Tail5.setRotationPoint(0.0F, -1.0F, 6.4F);
      this.Tail5.addBox(-2.0F, -2.2F, -1.3F, 4, 5, 5, 0.0F);
      this.setRotateAngle(this.Tail5, 0.4098033F, 0.0F, 0.0F);
      this.legMidR2 = new AdvancedModelRenderer(this, 11, 50);
      this.legMidR2.mirror = true;
      this.legMidR2.setRotationPoint(0.0F, 8.4F, 0.1F);
      this.legMidR2.addBox(-1.5F, 0.0F, -1.0F, 3, 12, 2, 0.0F);
      this.setRotateAngle(this.legMidR2, 0.0F, 0.0F, -1.1383038F);
      this.Tail4 = new AdvancedModelRenderer(this, 100, 20);
      this.Tail4.setRotationPoint(0.0F, 0.7F, 3.2F);
      this.Tail4.addBox(-2.5F, -3.5F, -0.1F, 5, 6, 7, 0.0F);
      this.setRotateAngle(this.Tail4, 0.27314404F, 0.0F, 0.0F);
      this.legMidR3_1 = new AdvancedModelRenderer(this, 11, 50);
      this.legMidR3_1.mirror = true;
      this.legMidR3_1.setRotationPoint(0.0F, 8.4F, 0.1F);
      this.legMidR3_1.addBox(-1.5F, 0.0F, -1.0F, 3, 12, 2, 0.0F);
      this.setRotateAngle(this.legMidR3_1, 0.0F, 0.0F, -1.1383038F);
      this.Tail9 = new AdvancedModelRenderer(this, 60, 17);
      this.Tail9.setRotationPoint(0.0F, -0.4F, 9.0F);
      this.Tail9.addBox(-4.0F, -2.7F, -0.1F, 8, 6, 7, 0.0F);
      this.setRotateAngle(this.Tail9, 0.18203785F, 0.0F, 0.0F);
      this.Body3 = new AdvancedModelRenderer(this, 36, 76);
      this.Body3.setRotationPoint(0.0F, 0.2F, 4.1F);
      this.Body3.addBox(-4.5F, -3.4F, -1.4F, 9, 9, 9, 0.0F);
      this.HeadBase.addChild(this.MandibleR);
      this.Body2.addChild(this.legTopR2_1);
      this.HeadBase.addChild(this.MandibleL);
      this.Body1.addChild(this.legTopR1);
      this.legMidR1_1.addChild(this.legBottomR1_1);
      this.legTopR1_1.addChild(this.legMidR1_1);
      this.Body1.addChild(this.legTopR1_1);
      this.HeadBase.addChild(this.EyeL);
      this.legMidR3.addChild(this.legBottomR3);
      this.Body3.addChild(this.legTopR3_1);
      this.legMidR3_1.addChild(this.legBottomR3_1);
      this.Body1.addChild(this.Neck1);
      this.Tail5.addChild(this.Tail6);
      this.legTopR1.addChild(this.legMidR1);
      this.legMidR2_1.addChild(this.legBottomR2_1);
      this.Body2.addChild(this.Body1);
      this.Tail6.addChild(this.Tail7);
      this.legMidR1.addChild(this.legBottomR1);
      this.Tail1.addChild(this.Tail2);
      this.HeadBase.addChild(this.EyeR);
      this.Body3.addChild(this.legTopR3);
      this.Tail9.addChild(this.Stinger);
      this.legTopR2_1.addChild(this.legMidR2_1);
      this.legTopR3.addChild(this.legMidR3);
      this.Tail7.addChild(this.Tail8);
      this.Body2.addChild(this.legTopR2);
      this.Tail2.addChild(this.Tail3);
      this.legMidR2.addChild(this.legBottomR2);
      this.Body3.addChild(this.Tail1);
      this.Neck1.addChild(this.HeadBase);
      this.Tail4.addChild(this.Tail5);
      this.legTopR2.addChild(this.legMidR2);
      this.Tail3.addChild(this.Tail4);
      this.legTopR3_1.addChild(this.legMidR3_1);
      this.Tail8.addChild(this.Tail9);
      this.Body2.addChild(this.Body3);
      this.animator = ModelAnimator.create();
      this.updateDefaultPose();
   }

   public void renderAdult(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.Body2.render(f5);
   }

   public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.resetToDefaultPose();
      this.animator.update(entity);
      this.animator.setAnimation(EntityMyrmexSentinel.ANIMATION_GRAB);
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -65.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Neck1, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1, -14.0F, 5.0F, 10.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1_1, -14.0F, -5.0F, -10.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1, -41.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1_1, -41.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1, 67.0F, 20.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1_1, 67.0F, -20.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(5);
      this.animator.setAnimation(EntityMyrmexSentinel.ANIMATION_STING);
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -36.0F, -15.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Body2, 0.0F, -31.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Body3, 0.0F, -13.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail1, 20.0F, 31.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail2, 52.0F, 15.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail3, 57.0F, 2.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail4, 18.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail5, 23.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail6, 5.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail7, 23.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail8, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail9, 10.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Stinger, 107.0F, 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -36.0F, 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -36.0F, 15.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Body2, 0.0F, 31.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Body3, 0.0F, 13.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail1, 20.0F, -31.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail2, 52.0F, -15.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail3, 57.0F, -2.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail4, 18.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail5, 23.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail6, 5.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail7, 23.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail8, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Tail9, 10.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Stinger, 107.0F, 0.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(10);
      this.animator.setAnimation(EntityMyrmexSentinel.ANIMATION_NIBBLE);
      this.animator.startKeyframe(5);
      ModelUtils.rotate(this.animator, this.Neck1, -50.0F, 0.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.HeadBase, 50.0F, 0.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.MandibleR, 0.0F, 35.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.MandibleL, 0.0F, -35.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotate(this.animator, this.Neck1, 30.0F, 0.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.HeadBase, -30.0F, 0.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.MandibleR, 0.0F, -50.0F, 0.0F);
      ModelUtils.rotate(this.animator, this.MandibleL, 0.0F, 50.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.setAnimation(EntityMyrmexSentinel.ANIMATION_SLASH);
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -65.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Neck1, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1, 24.0F, 20.0F, 30.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1, -98.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1, 70.0F, 20.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -65.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Neck1, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1_1, 24.0F, -20.0F, -30.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1_1, -98.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1_1, 70.0F, -20.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -65.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Neck1, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1, 24.0F, 20.0F, 30.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1, -98.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1, 70.0F, 20.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.startKeyframe(5);
      ModelUtils.rotateFrom(this.animator, this.Body1, -65.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.Neck1, 0.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legTopR1_1, 24.0F, -20.0F, -30.0F);
      ModelUtils.rotateFrom(this.animator, this.legMidR1_1, -98.0F, 0.0F, 0.0F);
      ModelUtils.rotateFrom(this.animator, this.legBottomR1_1, 70.0F, -20.0F, 0.0F);
      this.animator.endKeyframe();
      this.animator.resetKeyframe(5);
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
      EntityMyrmexSentinel myrmex = (EntityMyrmexSentinel)entity;
      AdvancedModelRenderer[] TAIL = new AdvancedModelRenderer[]{this.Tail1, this.Tail2, this.Tail3, this.Tail4, this.Tail5, this.Tail6, this.Tail7, this.Tail8, this.Tail9, this.Stinger};
      AdvancedModelRenderer[] NECK = new AdvancedModelRenderer[]{this.Neck1, this.HeadBase};
      AdvancedModelRenderer[] ARML1 = new AdvancedModelRenderer[]{this.legTopR1, this.legMidR1, this.legBottomR1};
      AdvancedModelRenderer[] LEGR2 = new AdvancedModelRenderer[]{this.legTopR2, this.legMidR2, this.legBottomR2};
      AdvancedModelRenderer[] LEGR3 = new AdvancedModelRenderer[]{this.legTopR3, this.legMidR3, this.legBottomR3};
      AdvancedModelRenderer[] ARMR1 = new AdvancedModelRenderer[]{this.legTopR1_1, this.legMidR1_1, this.legBottomR1_1};
      AdvancedModelRenderer[] LEGL2 = new AdvancedModelRenderer[]{this.legTopR2_1, this.legMidR2_1, this.legBottomR2_1};
      AdvancedModelRenderer[] LEGL3 = new AdvancedModelRenderer[]{this.legTopR3_1, this.legMidR3_1, this.legBottomR3_1};
      float speed_walk = 0.9F;
      float speed_idle = myrmex.isHiding() ? 0.015F : 0.035F;
      float degree_walk = 0.5F;
      float degree_idle = myrmex.isHiding() ? 0.1F : 0.25F;
      if (entity.ridingEntity == null) {
         this.faceTarget(f3, f4, 2.0F, NECK);
      }

      this.chainWave(TAIL, speed_idle, degree_idle * 0.15F, 0.0D, f2, 1.0F);
      this.chainWave(NECK, speed_idle, degree_idle * -0.15F, 2.0D, f2, 1.0F);
      this.swing(this.MandibleR, speed_idle * 2.0F, degree_idle * -0.75F, false, 1.0F, 0.2F, f2, 1.0F);
      this.swing(this.MandibleL, speed_idle * 2.0F, degree_idle * -0.75F, true, 1.0F, 0.2F, f2, 1.0F);
      this.animateLeg(LEGR3, speed_walk, degree_walk, false, 0.0F, 1.0F, f, f1);
      this.animateLeg(LEGR2, speed_walk, degree_walk, true, 0.0F, 1.0F, f, f1);
      this.animateLeg(LEGL3, speed_walk, degree_walk, false, 1.0F, -1.0F, f, f1);
      this.animateLeg(LEGL2, speed_walk, degree_walk, true, 1.0F, -1.0F, f, f1);
      this.bob(this.Body2, speed_walk, degree_walk, false, f, f1);
      this.chainWave(ARML1, speed_idle, degree_idle * -0.25F, 0.0D, f2, 1.0F);
      this.chainWave(ARMR1, speed_idle, degree_idle * -0.25F, 0.0D, f2, 1.0F);
      this.progressRotation(this.legTopR1, (float)myrmex.holdingProgress, (float)Math.toRadians(35.0D), (float)Math.toRadians(30.0D), (float)Math.toRadians(10.0D));
      this.progressRotation(this.legTopR1_1, (float)myrmex.holdingProgress, (float)Math.toRadians(35.0D), (float)Math.toRadians(-30.0D), (float)Math.toRadians(-10.0D));
      this.progressRotation(this.legMidR1, (float)myrmex.holdingProgress, (float)Math.toRadians(-133.0D), 0.0F, 0.0F);
      this.progressRotation(this.legMidR1_1, (float)myrmex.holdingProgress, (float)Math.toRadians(-133.0D), 0.0F, 0.0F);
      this.progressRotation(this.legBottomR1, (float)myrmex.holdingProgress, (float)Math.toRadians(140.0D), (float)Math.toRadians(20.0D), 0.0F);
      this.progressRotation(this.legBottomR1_1, (float)myrmex.holdingProgress, (float)Math.toRadians(140.0D), (float)Math.toRadians(-20.0D), 0.0F);
      this.progressRotation(this.legTopR1, (float)myrmex.hidingProgress, (float)Math.toRadians(70.0D), 0.0F, (float)Math.toRadians(70.0D));
      this.progressRotation(this.legTopR1_1, (float)myrmex.hidingProgress, (float)Math.toRadians(70.0D), 0.0F, (float)Math.toRadians(-70.0D));
      this.progressRotation(this.Body1, (float)myrmex.hidingProgress, (float)Math.toRadians(-2.0D), 0.0F, 0.0F);
      this.progressPosition(this.Body1, (float)myrmex.hidingProgress, 0.0F, 1.7F, -4.0F);
      this.progressPosition(this.Body2, (float)myrmex.hidingProgress, 0.0F, 17.0F, 0.0F);
      this.progressRotation(this.Body2, (float)myrmex.hidingProgress, (float)Math.toRadians(5.0D), 0.0F, 0.0F);
      this.progressRotation(this.legTopR2, (float)myrmex.hidingProgress, (float)Math.toRadians(55.0D), (float)Math.toRadians(30.0D), (float)Math.toRadians(-7.0D));
      this.progressRotation(this.legTopR2_1, (float)myrmex.hidingProgress, (float)Math.toRadians(55.0D), (float)Math.toRadians(-30.0D), (float)Math.toRadians(7.0D));
      this.progressRotation(this.legTopR3, (float)myrmex.hidingProgress, (float)Math.toRadians(45.0D), (float)Math.toRadians(10.0D), (float)Math.toRadians(40.0D));
      this.progressRotation(this.legTopR3_1, (float)myrmex.hidingProgress, (float)Math.toRadians(45.0D), (float)Math.toRadians(-10.0D), (float)Math.toRadians(-40.0D));
      this.progressRotation(this.legMidR2, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(-140.0D));
      this.progressRotation(this.legMidR2_1, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(140.0D));
      this.progressRotation(this.legMidR3, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(146.0D));
      this.progressRotation(this.legMidR3_1, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(-146.0D));
      this.progressRotation(this.legBottomR2, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(146.0D));
      this.progressRotation(this.legBottomR2_1, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(-146.0D));
      this.progressRotation(this.legBottomR3, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(-156.0D));
      this.progressRotation(this.legBottomR3_1, (float)myrmex.hidingProgress, 0.0F, 0.0F, (float)Math.toRadians(156.0D));
      this.progressRotation(this.HeadBase, (float)myrmex.hidingProgress, (float)Math.toRadians(-15.0D), 0.0F, 0.0F);
      this.progressPosition(this.HeadBase, (float)myrmex.hidingProgress, 0.0F, 0.0F, -4.4F);
      this.progressRotation(this.Tail1, (float)myrmex.hidingProgress, (float)Math.toRadians(-20.0D), 0.0F, (float)Math.toRadians(-46.0D));
      this.progressRotation(this.Tail2, (float)myrmex.hidingProgress, (float)Math.toRadians(26.0D), 0.0F, 0.0F);
      this.progressRotation(this.Tail3, (float)myrmex.hidingProgress, (float)Math.toRadians(40.0D), 0.0F, (float)Math.toRadians(-30.0D));
      this.progressRotation(this.Tail4, (float)myrmex.hidingProgress, (float)Math.toRadians(25.0D), 0.0F, (float)Math.toRadians(-18.0D));
      this.progressRotation(this.Tail5, (float)myrmex.hidingProgress, (float)Math.toRadians(23.0D), 0.0F, 0.0F);
      this.progressRotation(this.Tail6, (float)myrmex.hidingProgress, (float)Math.toRadians(10.0D), (float)Math.toRadians(-15.0D), (float)Math.toRadians(33.0D));
      this.progressRotation(this.Tail7, (float)myrmex.hidingProgress, (float)Math.toRadians(23.0D), 0.0F, 0.0F);
      this.progressRotation(this.Tail8, (float)myrmex.hidingProgress, (float)Math.toRadians(-20.0D), (float)Math.toRadians(-45.0D), (float)Math.toRadians(85.0D));
   }

   private void animateLeg(AdvancedModelRenderer[] models, float speed, float degree, boolean reverse, float offset, float weight, float f, float f1) {
      this.flap(models[0], speed, degree * 0.4F, reverse, offset, weight * 0.2F, f, f1);
      this.flap(models[1], speed, degree * 2.0F, reverse, offset, weight * -0.4F, f, f1);
      this.flap(models[1], speed, -degree * 1.2F, reverse, offset, weight * 0.5F, f, f1);
      this.walk(models[0], speed, degree, reverse, offset, 0.0F, f, f1);
   }

   public ModelRenderer[] getHeadParts() {
      return new ModelRenderer[]{this.Neck1, this.HeadBase};
   }
}
